name: trgb_gui
channels:
  - conda-forge
  - defaults
dependencies:
  - "python>3.9"
  - "pyqt>5,<6"
  - fpdf2
  - matplotlib
  - numpy
  - pandas
  - pillow
  - scipy
  - seaborn
  - jupyter
  - jupyterlab
